trigger:
  branches:
    include: [main, master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.4.0

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py38]
    os: windows
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37, py38, py39, py310]
    os: linux
